In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dff = pd.read_csv("/content/drive/MyDrive/Fake.csv")
dft = pd.read_csv("/content/drive/MyDrive/True.csv")

In [ ]:
dff.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [ ]:
dft.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [ ]:
dff['class']=0
dft['class']=1
df=pd.concat([dff,dft],axis=0)
df

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text    subject  \
0      Donald Trump just couldn t wish all Americans ...       News   
1      House Intelligence Committee Chairman Devin Nu...       News   
2      On Friday, it was revealed that former Milwauk...       News   
3      On Christmas day, Donald Trump announced that ...       News   
4      Pope Francis used his annual Christmas Day mes...       News   
...                                                  ...        ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...  worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...  worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...  worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews   

                    date  class  
0      December 31, 2017      0  
1      December 31, 2017      0  
2      December 30, 2017      0  
3      December 29, 2017      0  
4      December 25, 2017      0  
...                  ...    ...  
21412   August 22, 2017       1  
21413   August 22, 2017       1  
21414   August 22, 2017       1  
21415   August 22, 2017       1  
21416   August 22, 2017       1  

[44898 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44898 entries, 0 to 21416
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   class    44898 non-null  int64 
dtypes: int64(1), object(4)
memory usage: 2.1+ MB


In [ ]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
class      0
dtype: int64

In [ ]:
df['content']=df['title']+df['text']
df['content'].astype('str')
df.drop(['title','text'],axis=1)

subject               date  class  \
0           News  December 31, 2017      0   
1           News  December 31, 2017      0   
2           News  December 30, 2017      0   
3           News  December 29, 2017      0   
4           News  December 25, 2017      0   
...          ...                ...    ...   
21412  worldnews   August 22, 2017       1   
21413  worldnews   August 22, 2017       1   
21414  worldnews   August 22, 2017       1   
21415  worldnews   August 22, 2017       1   
21416  worldnews   August 22, 2017       1   

                                                 content  
0       Donald Trump Sends Out Embarrassing New Year’...  
1       Drunk Bragging Trump Staffer Started Russian ...  
2       Sheriff David Clarke Becomes An Internet Joke...  
3       Trump Is So Obsessed He Even Has Obama’s Name...  
4       Pope Francis Just Called Out Donald Trump Dur...  
...                                                  ...  
21412  'Fully committed' NATO backs new U.S. approach...  
21413  LexisNexis withdrew two products from Chinese ...  
21414  Minsk cultural hub becomes haven from authorit...  
21415  Vatican upbeat on possibility of Pope Francis ...  
21416  Indonesia to buy $1.14 billion worth of Russia...  

[44898 rows x 4 columns]

In [ ]:
df.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  class                                            content  
0  December 31, 2017      0   Donald Trump Sends Out Embarrassing New Year’...  
1  December 31, 2017      0   Drunk Bragging Trump Staffer Started Russian ...  
2  December 30, 2017      0   Sheriff David Clarke Becomes An Internet Joke...  
3  December 29, 2017      0   Trump Is So Obsessed He Even Has Obama’s Name...  
4  December 25, 2017      0   Pope Francis Just Called Out Donald Trump Dur...

In [ ]:
import re
import string

In [ ]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]','',text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+','',text)
    text = re.sub('<.*?>+',b'',text)
    text = re.sub('[%s]' % re.escape(string.punctuation),'',text)
    text = re.sub('\w*\d\w*','',text)
    return text

In [ ]:
df['content'].astype('str')
df['content'] = df['content'].apply(wordopt)

In [ ]:
x=df['content']
y=df['class']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
lr=LogisticRegression()
lr.fit(xv_train,y_train)
pred=lr.predict(xv_test)
print("Logistic Regression")
print("accuracy:", accuracy_score(y_test,pred))
print("confusion_matrix:\n", confusion_matrix(y_test,pred))
print("classification_report:\n", classification_report(y_test,pred))
print('\n')

Logistic Regression
accuracy: 0.9870824053452116
confusion_matrix:
 [[5815   80]
 [  65 5265]]
classification_report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      5895
           1       0.99      0.99      0.99      5330

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225





In [ ]:
rf=RandomForestClassifier(random_state=42)
rf.fit(xv_train,y_train)
pred=rf.predict(xv_test)
print("Random Forest Classifier")
print("accuracy:", accuracy_score(y_test,pred))
print("confusion_matrix:\n", confusion_matrix(y_test,pred))
print("classification_report:\n", classification_report(y_test,pred))
print('\n')

Random Forest Classifier
accuracy: 0.9893095768374165
confusion_matrix:
 [[5851   44]
 [  76 5254]]
classification_report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      5895
           1       0.99      0.99      0.99      5330

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225





In [ ]:

dt=DecisionTreeClassifier()
dt.fit(xv_train,y_train)
pred=dt.predict(xv_test)
print(" Decision Tree Classifier")
print("accuracy:", accuracy_score(y_test,pred))
print("confusion_matrix:\n", confusion_matrix(y_test,pred))
print("classification_report:\n", classification_report(y_test,pred))
print('\n')

 Decision Tree Classifier
accuracy: 0.9951893095768374
confusion_matrix:
 [[5869   26]
 [  28 5302]]
classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      5895
           1       1.00      0.99      0.99      5330

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225





In [ ]:
nb= MultinomialNB()
nb.fit(xv_train,y_train)
pred=nb.predict(xv_test)
print("multinomial naive bayes")
print("accuracy:", accuracy_score(y_test,pred))
print("confusion_matrix:\n", confusion_matrix(y_test,pred))
print("classification_report:\n", classification_report(y_test,pred))
print('\n')

multinomial naive bayes
accuracy: 0.9355011135857461
confusion_matrix:
 [[5630  265]
 [ 459 4871]]
classification_report:
               precision    recall  f1-score   support

           0       0.92      0.96      0.94      5895
           1       0.95      0.91      0.93      5330

    accuracy                           0.94     11225
   macro avg       0.94      0.93      0.94     11225
weighted avg       0.94      0.94      0.94     11225





In [ ]:
gb=GradientBoostingClassifier(
    random_state=0
)
gb.fit(xv_train,y_train)
pred=gb.predict(xv_test)
print("Gradient boosting")
print("accuracy:", accuracy_score(y_test,pred))
print("confusion_matrix:\n", confusion_matrix(y_test,pred))
print("classification_report:\n", classification_report(y_test,pred))
print('\n')

Gradient boosting
accuracy: 0.9952783964365256
confusion_matrix:
 [[5857   38]
 [  15 5315]]
classification_report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00      5895
           1       0.99      1.00      1.00      5330

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225





In [ ]:
def output_lable(n):
    if n==0:
        return "Fake"
    elif n==1:
        return "Real"

def manual_testing(news, models):
    testing_news = {"content": [news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["content"] = new_def_test["content"].apply(wordopt)
    new_x_test = new_def_test["content"]
    new_xv_test = vectorization.transform(new_x_test)

    for model_name, model in models.items():
        pred = model.predict(new_xv_test)
        pred_label = output_lable(pred[0])
        print(f"{model_name}: {pred_label}")

In [ ]:
news = str(input())
models = {
    "Logistic Regression": lr,
    "Random Forest Classifier": rf,
    "Decision Tree Classifier": dt,
    "Multinomial Naive Bayes": nb,
    "Gradient Boosting": gb
}
manual_testing(news, models)

UK woman detained by ICE for 6 weeks despite valid US visa: ‘Agents get bonus’
Logistic Regression: Fake
Random Forest Classifier: Fake
Decision Tree Classifier: Fake
Multinomial Naive Bayes: Fake
Gradient Boosting: Fake
